import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactQueryProvider } from '@/lib/reactQueryProvider';
import { OpenAPIProvider } from '@/context/OpenAPIContext';
import { SettingsProvider } from '@/context/SettingsContext';
import OpenAPIDebug from '@/components/dev/OpenAPIDebug';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <OpenAPIProvider url="/api/openapi.yaml">
          <ReactQueryProvider>
            <SettingsProvider>
              <OpenAPIDebug />
              {children}
            </SettingsProvider>
          </ReactQueryProvider>
        </OpenAPIProvider>
      </body>
    </html>
  );
}
