openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
paths:
  /login:
    get:
      summary: Login endpoint (GET)
      responses:
        '200':
          description: Login page or info
    post:
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Successful login
        '401':
          description: Unauthorized
components: {}
