name: CI

on:
  push:
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint
      - run: npm run type-check
      - run: npm test
      - run: |
          npx vitest run --coverage --coverageReporters=text --coverageReporters=lcov \
            --coverageThreshold='{"global": {"lines": 90, "branches": 90}}'

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: cd frontend && npm ci
      - run: npm run lint
      - run: npm run type-check
      - run: npm test
      - name: Fetch OpenAPI schema
        run: |
          if [ -n "${{ secrets.NEXT_PUBLIC_API_SCHEMA_URL }}" ]; then
            NEXT_PUBLIC_API_SCHEMA_URL="${{ secrets.NEXT_PUBLIC_API_SCHEMA_URL }}" npm --prefix frontend run fetch-schema
          else
            echo "NEXT_PUBLIC_API_SCHEMA_URL not set, skipping fetch-schema."
          fi
      - name: Generate API types
        run: npm --prefix frontend run generate-types
      - name: Check OpenAPI type drift
        run: |
          npx openapi-typescript frontend/public/api/openapi.yaml --output types/openapi.d.ts
          git diff --exit-code types/openapi.d.ts
      - name: Run frontend tests
        run: npm --prefix frontend run test

  e2e:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint
      - run: npm run type-check
      - run: npm test
      - name: Run Playwright tests with A11y
        run: npm run test:e2e
      - name: Check schema freshness
        run: |
          if [ -n "${{ secrets.NEXT_PUBLIC_API_SCHEMA_URL }}" ]; then
            NEXT_PUBLIC_API_SCHEMA_URL="${{ secrets.NEXT_PUBLIC_API_SCHEMA_URL }}" node scripts/check-schema-fresh.js
          else
            echo "NEXT_PUBLIC_API_SCHEMA_URL not set, skipping schema freshness check."
          fi
      - name: Start frontend for Lighthouse
        run: npm --prefix frontend run start &
      - name: Run Lighthouse CI
        run: npm --prefix frontend run lhci:autorun
