name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run basic build
        run: npm run build || echo "No build script"
      - name: Run tests
        run: npm test || echo "No tests present"
