name: Component Validation

on:
  pull_request:
    paths:
      - 'frontend/src/components/**'
      
jobs:
  validate-components:
    # Temporary workaround: use ubuntu-22.04 runner due to missing upload-artifact IAP on ubuntu-24.04 (May 2025)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: Run component verification
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          if [ -z "$BASE_SHA" ] || ! git cat-file -e $BASE_SHA; then
            BASE_SHA=$(git rev-parse origin/main)
          fi
          CHANGED_DIRS=$(git diff --name-only $BASE_SHA ${{ github.sha }} | grep -oP 'frontend/src/components/\K[^/]+' | sort -u)
          for DIR in $CHANGED_DIRS; do
            ./scripts/verify-component.sh $DIR
          done
        
      - name: Run tests for changed components
        run: |
          BASE_SHA=${{ github.event.pull_request.base.sha }}
          if [ -z "$BASE_SHA" ] || ! git cat-file -e $BASE_SHA; then
            BASE_SHA=$(git rev-parse origin/main)
          fi
          CHANGED_DIRS=$(git diff --name-only $BASE_SHA ${{ github.sha }} | grep -oP 'frontend/src/components/\K[^/]+' | sort -u)
          for DIR in $CHANGED_DIRS; do
            npm test -- --testPathPattern=$DIR
          done
        working-directory: ./frontend

  tech-debt-check:
    # Temporary workaround: use ubuntu-22.04 runner due to missing upload-artifact IAP on ubuntu-24.04 (May 2025)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
      - name: Setup Node.js
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610
        with:
          node-version: '18'
          
      - name: Run technical debt analysis
        run: |
          node ./scripts/analyze-tech-debt.js > tech-debt-report.md
          
      - name: Upload tech debt report
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32
        with:
          name: tech-debt-report
          path: tech-debt-report.md
