name: Component Validation

on:
  pull_request:
    paths:
      - 'frontend/src/components/**'
      
jobs:
  validate-components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
        
      - name: Run component verification
        run: |
          # Get list of changed component directories
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -oP 'frontend/src/components/\K[^/]+' | sort -u)
          
          for DIR in $CHANGED_DIRS; do
            ./scripts/verify-component.sh $DIR
          done
        
      - name: Run tests for changed components
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -oP 'frontend/src/components/\K[^/]+' | sort -u)
          
          for DIR in $CHANGED_DIRS; do
            npm test -- --testPathPattern=$DIR
          done
        working-directory: ./frontend

  tech-debt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Run technical debt analysis
        run: |
          node ./scripts/analyze-tech-debt.js > tech-debt-report.md
          
      - name: Upload tech debt report
        uses: actions/upload-artifact@v3
        with:
          name: tech-debt-report
          path: tech-debt-report.md
