name: Report Failures
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *' # every hour
jobs:
  report-failures:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh
      - name: Install dependencies
        run: npm ci
      - name: Run report-failures
        id: report
        run: |
          npx node scripts/projectctl.js report-failures \
            --workflow ci-status.yml \
            --branch main \
            --status failure \
            --format text \
            --since 1h
        continue-on-error: true
      - name: Annotate PR with failure summary
        if: steps.report.outcome == 'failure' || steps.report.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync(process.env.GITHUB_WORKSPACE + '/github_workflow_failure_report.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `### Workflow Failure Summary\n\n${summary}`
            });
      - name: Fail if failures found
        if: steps.report.outcome == 'failure'
        run: exit 1
